password = "" # sower password

[client]
address = "" # aa.bb.cc, socks5h://127.0.0.1:1080
dns_upstream = "" # keep empty to set via dhcp, not effective in any environment
http_proxy = ""
socks5 = ""

[client.port_forward]
# eg: ":2222"="aa.bb.cc:22"

[client.router]
block_refs = [
  "https://cdn.jsdelivr.net/gh/pexcn/daily@gh-pages/adlist/adlist.txt",
]
detect_level = 0 # [-4, 4], the bigger the harder to add
direct_cird_refs = [
  "https://cdn.jsdelivr.net/gh/pexcn/daily@gh-pages/chnroute/chnroute.txt",
]
direct_list = [
  "**.in-addr.arpa",
  "imap.*.*",
  "imap.*.*.*",
  "smtp.*.*",
  "smtp.*.*.*",
  "pop.*.*",
  "pop.*.*.*",
  "**.cn",
]
direct_refs = [
  "https://cdn.jsdelivr.net/gh/pexcn/daily@gh-pages/chinalist/chinalist.txt",
]
proxy_list = [
  "**.google.*",
  "**.goo.gl",
  "**.googleusercontent.com",
  "**.googleapis.com",
  "*.googlesource.com",
  "**.youtube.com",
  "**.ytimg.com",
  "**.ggpht.com",
  "**.googlevideo.com",
  "**.facebook.com",
  "**.fbcdn.net",
  "**.twitter.com",
  "**.twimg.com",
  "**.blogspot.com",
  "**.appspot.com",
  "**.wikipedia.org",
  "*.cloudfront.net",
  "**.amazon.com",
  "**.amazonaws.com",
  "*.githubusercontent.com",
  "*.githubassets.com",
  "*.github.*",
]
proxy_refs = [
  "https://cdn.jsdelivr.net/gh/pexcn/daily@gh-pages/gfwlist/gfwlist.txt",
]

[server]
cert_email = "" # eg: user@aa.bb.cc
cert_file = "" # eg: /etc/ssl/server.crt
key_file = "" # eg: /etc/ssl/server.key
upstream = "" # eg: 127.0.0.1:8080
